[DATA-005] editted

diff --git a/.github/workflows/run_mlflow_script.yml b/.github/workflows/run_mlflow_script.yml
--- a/.github/workflows/run_mlflow_script.yml
+++ b/.github/workflows/run_mlflow_script.yml
@@ -32,59 +32,68 @@ jobs:
           echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
           echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV
 
-      - name: Extract CUSTOMER_ID, SKU, RUN_ID from Commit Message
-        run: |
-          COMMIT_MSG=$(git log -1 --pretty=%B)
-          CLEAN_MSG=$(echo "$COMMIT_MSG" | tr '\n' ' ')  # 모든 줄바꿈 제거
+      # - name: Extract CUSTOMER_ID, SKU, RUN_ID from Commit Message
+      #   run: |
+      #     COMMIT_MSG=$(git log -1 --pretty=%B)
+      #     CLEAN_MSG=$(echo "$COMMIT_MSG" | tr '\n' ' ')  # 모든 줄바꿈 제거
 
-          echo "📝 Commit Message: $CLEAN_MSG"
+      #     echo "📝 Commit Message: $CLEAN_MSG"
 
-          CUSTOMER_ID=$(echo "$CLEAN_MSG" | grep -oP '(?<=CUSTOMER_ID=)[a-zA-Z0-9]+' || true)
-          SKU=$(echo "$CLEAN_MSG" | grep -oP '(?<=SKU=)[\w-]+' || true)
-          RUN_ID=$(echo "$CLEAN_MSG" | grep -oP '(?<=RUN_ID=)[\w-]+' || true)
+      #     CUSTOMER_ID=$(echo "$CLEAN_MSG" | grep -oP '(?<=CUSTOMER_ID=)[a-zA-Z0-9]+' || true)
+      #     SKU=$(echo "$CLEAN_MSG" | grep -oP '(?<=SKU=)[\w-]+' || true)
+      #     RUN_ID=$(echo "$CLEAN_MSG" | grep -oP '(?<=RUN_ID=)[\w-]+' || true)
  
 
  
-          if [ -z "$CUSTOMER_ID" ] || [ -z "$SKU" ] || [ -z "$RUN_ID" ]; then
-            echo "🚫 필수 파라미터 누락! CUSTOMER_ID, SKU, RUN_ID 중 하나라도 없으면 워크플로우 중단"
-            echo "CUSTOMER_ID=$CUSTOMER_ID"
-            echo "SKU=$SKU"
-            echo "RUN_ID=$RUN_ID"
-            echo "skip_workflow=true" >> $GITHUB_ENV
-            exit 0
-          fi
+      #     if [ -z "$CUSTOMER_ID" ] || [ -z "$SKU" ] || [ -z "$RUN_ID" ]; then
+      #       echo "🚫 필수 파라미터 누락! CUSTOMER_ID, SKU, RUN_ID 중 하나라도 없으면 워크플로우 중단"
+      #       echo "CUSTOMER_ID=$CUSTOMER_ID"
+      #       echo "SKU=$SKU"
+      #       echo "RUN_ID=$RUN_ID"
+      #       echo "skip_workflow=true" >> $GITHUB_ENV
+      #       exit 0
+      #     fi
 
-          echo "✅ Extracted CUSTOMER_ID=$CUSTOMER_ID, SKU=$SKU, RUN_ID=$RUN_ID"
+      #     echo "✅ Extracted CUSTOMER_ID=$CUSTOMER_ID, SKU=$SKU, RUN_ID=$RUN_ID"
 
-          echo "CUSTOMER_ID=$CUSTOMER_ID" >> $GITHUB_ENV
-          echo "SKU=$SKU" >> $GITHUB_ENV
-          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
+      #     echo "CUSTOMER_ID=$CUSTOMER_ID" >> $GITHUB_ENV
+      #     echo "SKU=$SKU" >> $GITHUB_ENV
+      #     echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
 
 
 
-      - name: Fetch new and old metrics
+    - name: Fetch new and old metrics
+    
+      if: env.skip_workflow != 'true'
+      env:
+        CUSTOMER_ID: ${{ env.CUSTOMER_ID }}
+        SKU: ${{ env.SKU }}
+        RUN_ID: ${{ env.RUN_ID }}
+        MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
+        MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
+      run: |
+        echo "Fetching metrics using Python..."
+        cd modeling/commons
+        python get_metrics.py >> metrics_output.txt
 
-        if: env.skip_workflow != 'true'
+        # Parse the last line
+        last_line=$(tail -n 1 metrics_output.txt)
 
-        env:
-          CUSTOMER_ID: ${{ env.CUSTOMER_ID }}
-          SKU: ${{ env.SKU }}
-          RUN_ID: ${{ env.RUN_ID }}
-          MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
-          MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
-        run: |
-          echo "Fetching metrics using Python..."
-          cd modeling/commons
-          python get_metrics.py >> metrics_output.txt
-          
-          # Read the metrics from the output file
-          new_metric=$(cat metrics_output.txt | grep "NEW_METRIC" | cut -d '=' -f2)
-          old_metric=$(cat metrics_output.txt | grep "OLD_METRIC" | cut -d '=' -f2)
-          is_first_model=$(grep "IS_FIRST_MODEL" metrics_output.txt | cut -d '=' -f2)
+        IFS=',' read -r customer store sku new_metric_str old_metric_str is_first_str <<< "$last_line"
 
-          echo "NEW_METRIC=$new_metric" >> $GITHUB_ENV
-          echo "OLD_METRIC=$old_metric" >> $GITHUB_ENV
-          echo "IS_FIRST_MODEL=$is_first_model" >> $GITHUB_ENV
+        new_metric=$(echo "$new_metric_str" | cut -d '=' -f2)
+        old_metric=$(echo "$old_metric_str" | cut -d '=' -f2)
+        is_first_model=$(echo "$is_first_str" | cut -d '=' -f2)
+
+        echo "✅ Parsed metrics:"
+        echo "NEW_METRIC=$new_metric"
+        echo "OLD_METRIC=$old_metric"
+        echo "IS_FIRST_MODEL=$is_first_model"
+
+        echo "NEW_METRIC=$new_metric" >> $GITHUB_ENV
+        echo "OLD_METRIC=$old_metric" >> $GITHUB_ENV
+        echo "IS_FIRST_MODEL=$is_first_model" >> $GITHUB_ENV
+
 
 
       - name: Compare new vs old metrics
@@ -108,32 +117,32 @@ jobs:
       
 
 
-      - name: Slack notify on metric degradation
-        if: env.metric_check == 'failure'
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK__CICD_DATA_NOTI_DEV }}
-          SLACK_COLOR: "#FF0000"
-          SLACK_TITLE: "[${{ env.CUSTOMER_ID }}, ${{ env.SKU }}, ${{ env.RUN_ID}}] ⚠️ Model Performance Degraded or Same"
-          SLACK_MESSAGE: "New metric ${{ env.NEW_METRIC }} is worse than old one or same as before ${{ env.OLD_METRIC }}. Check model performance. :warning:"
+      # - name: Slack notify on metric degradation
+      #   if: env.metric_check == 'failure'
+      #   uses: rtCamp/action-slack-notify@v2
+      #   env:
+      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK__CICD_DATA_NOTI_DEV }}
+      #     SLACK_COLOR: "#FF0000"
+      #     SLACK_TITLE: "[${{ env.CUSTOMER_ID }}, ${{ env.SKU }}, ${{ env.RUN_ID}}] ⚠️ Model Performance Degraded or Same"
+      #     SLACK_MESSAGE: "New metric ${{ env.NEW_METRIC }} is worse than old one or same as before ${{ env.OLD_METRIC }}. Check model performance. :warning:"
 
 
-      - name: Slack notify on metric improvement
-        if: env.metric_check == 'success'
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK__CICD_DATA_NOTI_DEV }}
-          SLACK_COLOR: "#36A64F"
-          SLACK_TITLE: "[${{ env.CUSTOMER_ID }}, ${{ env.SKU }}, ${{ env.RUN_ID}}] ✅ Model Performance Improved"
-          SLACK_MESSAGE: "New metric ${{ env.NEW_METRIC }} is same or better than old one ${{ env.OLD_METRIC }}. All good! :rocket:"
+      # - name: Slack notify on metric improvement
+      #   if: env.metric_check == 'success'
+      #   uses: rtCamp/action-slack-notify@v2
+      #   env:
+      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK__CICD_DATA_NOTI_DEV }}
+      #     SLACK_COLOR: "#36A64F"
+      #     SLACK_TITLE: "[${{ env.CUSTOMER_ID }}, ${{ env.SKU }}, ${{ env.RUN_ID}}] ✅ Model Performance Improved"
+      #     SLACK_MESSAGE: "New metric ${{ env.NEW_METRIC }} is same or better than old one ${{ env.OLD_METRIC }}. All good! :rocket:"
 
  
 
-      - name: Slack notify on first model registration
-        if: env.IS_FIRST_MODEL == 'true'
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK__CICD_DATA_NOTI_DEV }}
-          SLACK_COLOR: "#439FE0"
-          SLACK_TITLE: "[${{ env.CUSTOMER_ID }}, ${{ env.SKU }}, ${{ env.RUN_ID}}] 📦 First Model Registered"
-          SLACK_MESSAGE: "No previous model found. This run is registered as the first version for ${{ env.CUSTOMER_ID }} & ${{ env.SKU }}."
+      # - name: Slack notify on first model registration
+      #   if: env.IS_FIRST_MODEL == 'true'
+      #   uses: rtCamp/action-slack-notify@v2
+      #   env:
+      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK__CICD_DATA_NOTI_DEV }}
+      #     SLACK_COLOR: "#439FE0"
+      #     SLACK_TITLE: "[${{ env.CUSTOMER_ID }}, ${{ env.SKU }}, ${{ env.RUN_ID}}] 📦 First Model Registered"
+      #     SLACK_MESSAGE: "No previous model found. This run is registered as the first version for ${{ env.CUSTOMER_ID }} & ${{ env.SKU }}."
